/**
 *  use  
 *  {{ $t("message.hello") }}
 *   this.$i18n.locale='zh'
 */
(function(win) {
    Vue.use(VueI18n);
    var messages = {
        en: {
            message: {
                changeSucc: "Modified success",
                changeFail: "Modification failed",
                deleteSucc: "Deleted success",
                deleteFail: "Deleted fail",
                noAuthority: "No authority",
                addSucc: "Add success",
                addFail: "Add fail",
                saveSucc: "Save success",
                saveFail: "Save fail",
                confirmDel: "Are you sure you want to delete it?",
                selectCustomersTip: "Please select your customers",
                fillGroupNameTip: "Fill in the group name",
                pwdRule: "Password less than 6 bits",
                usernameRule: "User names are composed of 4 to 32 digits of numbers and letters.",
                fullComplete: "Please complete the form.",
                fullDevName: "Please fill in the name of the equipment.",
                userExists: "The user already exists",
                resetPwdTips: "Password reset to:123456",
                plSelectTime: "Please choose the time",
                IDRepeat: "Device ID repeat",
                IDError: "Device ID error",
                reqFail: "Request fail",
                selectCorrectAccount: "Please select the correct account!",
                networkError: "network error",
                exportSucceeded: "Export succeeded",
                exportFailed: "Export failed",
                useTemplateTips: "Please use the template provided by us",
                selectDeviceTtypeTips: "Please select device type",
                addDevice500Tips: "No more than 500 devices can be added at one time",
                deviceIdTips: "The serial number must be a number or a letter",
            },
            login: {
                title: "Location video service platform",
                chinese: "Chinese",
                english: "英文",
                companyLogin: "User",
                deviceLogin: "Device",
                pememberPwd: "Remember password",
                logining: "Login",
                experience: "experience",
                inputUsername: "Please enter your account number.",
                inputDeviceNumber: "Please enter the device number.",
                inputPassword: "Please input a password",
                wechatApplet: "Wechat applet",
                step1: "1.Search for gps51 applet",
                step2: "2.Or scan QR Code",
                step3: "3.For iPhone/Android",
                error_1: "Incorrect account format",
                error_2: "Incorrect password format",
                error_3: "Login failed",
                error_4: "Error in account or password",
                error_5: "No landing",
                error_6: "Account expired",
                appdownload: "App download",
                appstep1: "1.Search for gps51 app store",
                appstep2: "2.Or scan QR Code",
                appstep3: "3.For iPhone/Android",
                beiAn1: "Copyright © 2015-2017 gps51.com All Rights Reserved",
                beiAn2: "粤ICP备17068924号",
            },
            header: {
                monitor: "Monitor",
                reportForm: "Report",
                bgManager: "Management",
                systemParam: "System Params",
                hello: "Hello",
                changePwd: "Change Password",
                multiSiteLanding: "many login",
                ruleManagr: "RuleMgr",
                setting: "Setup",
                logout: "Logout",
                showCustomer: "Show customer name",
                setIntaival: "Refresh interval (min 5s)",
                oldPwd: "Old password",
                newPwd: "New password",
                confirmPwd: "Check password",
                submit: "Submit",
                changePwdSucc: "Successful password modification",
                error_1: "Password must not be less than four digits",
                error_2: "Password cannot be empty",
                error_3: "Two password inconsistencies",
                error_4: "Old password error",
                contact: "Contact",
                info: "Service info",
                name: "Servicer",
                phone: "Phone",
                wechat: "Wechat",
                email: "Email",
                yes:"Yes",
                no:"No",
            },
            alarm: {
                message: "Message",
                alarmMsg: "Alarm message",
                devMsg: "Device message",
                filterAlarmType: "Type of filter alarm",
                open: "open",
                max: "Maximization",
                min: "minimize",
                changeWin: "switch windows",
                filterAlarmTitle: "Filter alarm",
                releaseAlarmTitle: "Release alarm",
                errorNeedParams: "All parameters are mandatory",
                successfulRelease: "Successful release",
                devName: "Device Name",
                devNum: "Device Number",
                alarmTime: "Alarm Date",
                alarmCount: "Alarm Count",
                isDispose: "Dispose",
                action: "Action",
                alarmDispose: "Alarm Dispose",
                overdueTime: "Overdue Date",
                isOverdue: "Overdue",
                createTime: "Create time",
                content: 'Content',
                expirationInfo: 'ExpirationInfo',
                emergencyAlarm: 'EmergencyAlarm',
                voice: 'Voice',
                popup: 'Popup',
                emergencyAlarmSetting: 'EmergencyAlarmSetting',
            },
            monitor: {
                mapMode:'map mode',
                videoMode:'video mode',
                screenDisplay:'ScreenDisplay',
                regionSelection:'Region selection',
                defaultStyle:'DefaultStyle',
                midnightBlue:'MidnightBlue',
                stock:'Stock',
                devGroup: "Devices",
                ownerInfo:'ownerInfo',
                gotogroup:'goToGroup',
                play:'play',
                batteryMgr:'battery',
                weigh:'weigh',
                watermeter:'watermeter',
                videoSettings:'video settings',
                intercom:'Intercom',
                defaultGroup: "Default group",
                defaultCustomer: "Default customer",
                all: "All",
                online: "Online",
                offline: "Offline",
                placeholder: "Enter device name",
                edit: "Edit",
                track: "Track",
                following: "Stalker",
                more: "More",
                deviceCmd: "device cmd",
                siteProtection: "Site protection",
                fortify: "Fortify",
                cancel: "Cancel",
                cmdRecord: "Cmd record",
                recordForm: "Record form",
                devBaseInfo: "Basic Information",
                refreshAfter: "s after refresh",
                ranging: "Ranging",
                tools: "Tools",
                editDev: "Edit Device",
                phoneNumber: "Phone Number",
                remarks: "Remarks",
                confirm: "Confirm",
                customer: "Customer",
                groupName: "Group Name",
                devNumber: "Device Number",
                devName: "Device Name",
                factoryNum: "Factory Number",
                clientType: "Client Type",
                expireTime: "Expire Date",
                close: "Close",
                settingFence: "Setting up electronic fence",
                range: "range(m)",
                toSendCmd: "To send instructions",
                directivesSent: "Directives sent",
                settingFail: "Setup failed",
                noTrackError: "No track, no defence",
                rangeNumErr: "Range must be a number",
                queryCmdRecordErr: "Query instruction record failed",
                cancelFenceSucc: "Successful withdrawal",
                sendSucc: "Successful development",
                pwdErr: "Password error",
                sendCmdAbnormal: "Exceptions to issuing instructions",
                sendCmdNoCache: "The device is offline and instructions are not cached",
                sendCmdAlreadyCache: "The device is offline and the instructions are cached",
                changePwdSendCmd: "Send instructions after modifying the default password",
                noRecordTrack: 'The device did not report location information',
                reLogin: "Please re-login and automatically jump to the login page in 2 seconds",
                devNameMust: "Device name is mandatory",
                alarmRecords: "Alarm records",
                media: "Media",
                clearAllVideos:'Clear all videos',
                mute:'Mute',
                showAChannel:'Show a channel',
                showFourChannel:'Show four channel',
                showSixChannel:'Show six channel',
                showEightChannel:'Show eight channel',
                showNineChannel:'Show nine channel',
                showSixteenChannel:'Show sixteen channel',
                playAllVideos:'Play all videos',
                stopAllVideos:'Stop all videos',
                videoPlayback:'VideoBack',
                activeSafety:'ActiveSafety',
                recordingTips:'Recording, please speak',
                yuntai:'Yuntai',
                call:'Call',
                setup:'Set up',
                delete:'delete',
                color:'color',
                luminance:'luminance',
                contrastRatio:'contrast ratio',
                chroma:'chroma',
                saturation:'saturation',
                exposure:'exposure',
                default:'default',
                voice:'voice',
                monitor:'monitor',
                close:'close',
                open:'open',
                repressSpeak:'Repress speak',
                audioPlayerTip:'Please click the following button first',
                openJianTingTip:'Please turn on the monitor first',
                openJianTingTip1:'Monitoring is on, please press and hold to speak',
                browserDoesNotSupportRecording:'The browser does not support recording or no recording device is detected',
                closeSucc:'Closed successfully',
                openSucc:'Open successfully',
                openFail:'Failed to open, timeout or device is not online',
                jiantingYiclose:'Listening turned off',
                selectVideoDevice:'Please select a video device',
                channelIsNumber:'The channel number must be a number from 1 to 99',
                setupSucc:'Setup succeeded',
                setupFail:'Setup failed',
                querySucc:'query was successful',
                queryFail:'Query failed',
                theDeviceDidNotReturnData:'The device did not return data',
                CMD_SEND_RESULT_UNCONFIRM:'Sent successfully, no confirmation received',
                CMD_SEND_CONFIRMED:'send was successful',
                CMD_SEND_RESULT_PASSWORD_ERROR:'Password error',
                CMD_SEND_RESULT_OFFLINE_NOT_CACHE:'Device offline, not cached',
                CMD_SEND_RESULT_OFFLINE_CACHED:'Device offline, cached',
                CMD_SEND_RESULT_MODIFY_DEFAULT_PASSWORD:'The default password needs to be changed',
                CMD_SEND_RESULT_DETAIL_ERROR:'error:',
                CMD_SEND_OVER_RETRY_TIMES:'Three attempts to send failed',
                CMD_SEND_SYNC_TIMEOUT:'Send Timeout',
                transferSucc:'Transfer successful',
                transferFail:'Transfer failed',
                fillParameters:'Please fill in all parameters',
                channel:'channel',
                mapNotSupported:'The map does not support this function temporarily',
                deviceOffline:'Device offline',
                deviceNotVideo:'The device is not a video player',
                notEnabled:" [NotEnabled] ",
            },
            video:{
                accOpen:'ACC open,',
                accClose:'ACC clase,',
                requestTimeout:'request timeout',
                requestPlayTimeout:'Request playback timeout...',
                requestPlaySucc:'Request to play successfully, please wait...',
                error:'An error was encountered while requesting data',
                requestPlay:'Requesting playback',
                play:'Start playing',
                playing:'Playing',
                pause:'Pause',
                waiting:'Waiting for data',
                pausePlay:'Pause playback',
                threeMinutes:'It has been playing for three minutes. It will be suspended',
                notSupportCanvas:"Your browser does not support canvas at this time",
            },
            reportForm: {
                empty:'Empty', 
                clean:'Clean',
                total: "Total : ",
                maxMileage: "End Mileage",
                minMileage: "Start Mileage",
                totalMileage: "Total Mileage",
                index: "index",
                date: "Date",
                time: "Date",
                drivingReport: "Driving Report",
                cmdReport: "Directive Report",
                posiReport: "Position Report",
                mileageReport: "Mileage Report",
                mileage: "Mileage",
                reportmileagesummary: "Mileage Summary",
                reportmileagedetail: "Mileage Detail",
                parkDetails: "Park Details",
                warningReport: "Alarm Report",
                allAlarm: "All Alarm",
                phoneAlarm: "Phone Alarm",
                rechargeRecords: "Recharge records",
                selectTime: "Selection time",
                selectDev: "Selection Car ",
                toDay: "Today",
                yesterDay: "Yester day",
                threeDays: "Nearly three days",
                sevenDays: "Last seven days",
                query: "Query",
                intervalTime: "Interval time (minutes)",
                selectDevTip: "Please select equipment",
                noRecord: "No record",
                sendDate: "Send date",
                content: "Content",
                sendResult: "Result",
                lon: "Lon",
                lat: "Lat",
                direction: "Direction",
                speed: "Speed",
                status: "Status",
                posiType: "Positon Type",
                address: "Address",
                AddressDetails: "Details",
                getAddress: "Get Address",
                seePosi: "See position",
                startAlarmDate: "Start date",
                lastAlarmDate: "Last date",
                alarmInfo: "Alarm info",
                alarmCount: "Alarm count",
                isDispose: "Dispose",
                disposePerson: "Person",
                untreated: "Untreated",
                handled: "Handled",
                startDate: "Start date",
                endDate: "End date",
                parkDate: "Park date",
                d: "day",
                h: "h",
                m: "m",
                s: "s",
                acc: "Acc Report",
                accstatus: 'Acc State',
                duration: 'Duration',
                open: 'Open',
                stalling: 'Stalling',
                notEnabled: 'not enabled',
                accOffTime: 'ACC off time',
                accOnTime: 'ACC on time',
                accDetailed: 'Acc detailed',
                accCount: 'Acc count',
                accStatistics: 'Acc statistics',
                accDuration: 'Acc duration',
                ignitionStatistics: 'ignition-statistics',
                download:'Download',
                filter:'filter',
                beforeDay:'Before day',
                afterDay:'After day',
                voiceReport:'Voice report',
                messageReport:'Message report',
                rotationStatistics:'Rotation statistics',
                rotationDetails:'Rotation details',
                count:'Count',
                zzTimes:'Clockwise duration', 
                fzTimes:'Reversal duration',
                tzTimes:'Stop duration',
                zz:'Corotation',
                fz:'Reversal',
                tz:'Stall',
                wechatAlarm:'Wechat alarm',
                speedingReport:'Speeding report',
                speedingStatistics:'Speeding statistics',
                speedingDetails:'Speeding details',
                speedingDuration:'Speeding duration',
                speedingMileage:'Speeding mileage',
                speedingCount:'Speeding count',
                maxSpeed:'Max speed',
                minSpeed:'Min speed',
                speedingTrack:'Speeding track',
                onlineStatistics:'Online statistics',
                comprehensiveStatistics:'Comprehensive ',
                offlineReport:'Offline report',
                dailyVehicleOnlineRate:'Vehicle day online',
                dailyFleetOnlineRate:'fleet day online',
                monthlyVehicleOnlineRate:'Vehicle monthly online',
                operationStatus:'Operation status',
                updateTime:'Update time',
                lastAddress:'Last address',
                lastState:'Last state',
                notLocated:'Not located',
                located:'Located',
                selectAccount:'Select user',
                vehicleTotal:'Vehicle total',
                onlineTotal:'Online total',
                offlineTotal:'Offline total',
                locationTotal:'Location total',
                notLocationTotal:'Not location total',
                offlineDuration:"Offline duration",
                h1:"1h",
                h6:"6h",
                h12:"12h",
                d1:"1d",
                d7:"7d",
                d15:"5d",
                d30:"1m",
                d180:"0.5y",
                d365:"1y",
                offlineTime:"Offline time",
                downOfflineDuration:"Offline duration",
                ascriptionUser:"Ascription user",
                selectMonth:"Select month",
                onlineDaysAndTotalDays:"onlineDays / totalDays",
                onlineRate:"Online rate",
                onlineDate:"Online date",
                selectDate:"Select date",
                onlinequantityAndTotalquantity:"Online quantity / total quantity",
                dailyOnlineRate:"Daily online rate",
                selectGroup:"Please select group",
                insurMgr:'Insur management',
                insurRecord:'Insur record',
                salesRecord:'Sales records',
                all:'All',
                aeviewed:'Aeviewed',
                notReviewed:'notReviewed',
                exactSearch:'Exact search',
                exportData:'Export data',
                examine:'Examine',
                name:'name',
                idNumber:'identity',
                policyNumber:'Policy number',
                addDate:'date',
                purchaseMethod:'Purchase method',
                distributor:'distributor',
                distributorAddress:'distributor address',
                distributorPhone:'distributor phone',
                phonenum: 'using phone',
                usingaddress: 'using address', 
                brandtype: 'brand', 
                vinno: 'vinno', 
                gpsid: 'GPS',
                buycarday: 'buycar day', 
                carvalue: 'price', 
                insureprice: 'insure price', 
                insurefee: 'insurefee', 
                qualitycert: 'qualitycert',
                carpic: 'carpic',
                positivecardid: 'positivecard',
                negativecardid: 'negativecard',
                invoice: 'invoice',
                groupphoto: 'groupphoto',
                carkeypic: 'carkeypic',
                insurenotice: 'insurenotice',
                clickPreview: 'clickPreview',
                cancelAudit: 'cancelAudit',
                confirmAudit: 'confirmAudit',
                underReview: 'underReview',
                insureData: 'insure_data',
                tips:'Tips',
                tipsContent: "Do you want to delete this policy information!",

                storeNumber:'Store id',
                storeName:'Store name',
                cumulativeRecords:'Cumulative records',
                surplus:'surplus',
                exFactory:'exFactory',
                buyOneself:'buyOneself',
                year:'year',
                month:'month',
                insurePlaceholder:'input_user|phone|identity',
                oilReport:'Oil report',
                dayOilConsumption:'Day oil consumption',
                dateOilConsumption:'Date oil consumption',
                addOil:'Add oil',
                reduceOil:'Reduce oil',
                tempReport:'Temp report',
                logisticsReport:'Logistics report',
                driverWorkDetails:'Driver work details',
                oilConsumption:'Oil consumption',
                fuelVolume:'fuelVolume',
                oilLeakage:'oilLeakage',
                fuelConsumption100km:'100km Oil',
                soil:'Before oil(L)',
                eoil:'After oil(L)',
                lsoil:'Before oilConsumption(L)',
                leoil:'After oilConsumption(L)',
                saddress:'Start address(click)',
                eaddress:'End address(click)',
                totalOil:'totalOil(L)',
                oil1:"oil1(L)",
                oil2:"oil2(L)",
                oil:"oil",
                temp:'temp',
                temp1:'temp1',
                temp2:'temp2',
                temp3:'temp3',
                temp4:'temp4',
                averageTemp:'averageTemp',
                humi:'humi',
                drivername:'Driver name',
                cardinsertTime:'load time(insert)',
                cardinsertAddress:'load address(insert)',
                cardPullTime:'Unloading time(pull)',
                cardPullAddress:'Unloading address(pull)',
                workingHours: 'working hours',
                certificationcode: 'drive code',
                viewTrack: 'View track',
                queryAllAddress: 'Query all address',
            },
            bgMgr: {
                bindpwd: "Bind pwd",
                customerMgr: "Customer Manager",
                addCustomer: "Add Customer",
                queryCustomer: "Query Customer",
                groupMgr: "Group Manager",
                addGroup: "Add Group",
                queryGroup: "Query Group",
                userMgr: "User Manager",
                addUser: "Add User",
                queryUser: "Query User",
                devMgr: "Device Manager",
                addDev: "Add Device",
                queryDev: "Query Device",
                submit: "Submit",
                reset: "Reset",
                back: "Back",
                delete: "Delete",
                edit: "Edit",
                action: "Action",
                userTotal: "User Total",
                deviceTotal: "Device Total",
                groupTotal: "Group Total",
                addTime: "Add Time",
                creater: "creater",
                batchMgr: "batchManage",
                batchAdd: "Batch add",
                renewMgr: "Renew mgr",
                operateMgr: "Operate mgr",
                importOwnerInfo: "Import owner info",
                importInsureInfo: "Import insure info",
                importPolicyInfo: "Import policy info",
                importVin: "Import vin",
                importOfflineInsurePolicyInfo: "Import offline policy info",
                importSimInfo: "Import SIM",
                importDeviceName: "Import device name",
                repairMgr: "Repair mgr",
                addRepair: "Add repair record",
                repairRecord: "Repair records",
                allAevcieList: "All device",
                selectedDeviceList: "Selected device",
                transferGroupList: "Transfer user",
                result:"Result",
                exportDevice:"Export device",
                batchModification:"Batch edit",
                batchTransfer:"Batch transfer",
                batchModifyForwardingAddress:"batch edit forwarding address",
                batchEditDueDate:"Batch edit due date",
                batchResetPwd:"Batch reset pwd",
                batchEditDevType:"Batch modify device type",
                batchIssueCmd:"Batch issue cmd",
                forwardingType:"Forwarding type",
                parseHttp:"Parse HTTP",
                tcp:"TCP",
                passModel:"Pass model",
                deviceIDlastFour:"Last four",
                fixedPassword:"Fixed password",
                issueCmd:"Issuer cmd",
                cmdContent:"Cmd content",
                pwd:"password",
                sending:"Sending",
            },
            customer: {
                kehuName: "Customer name",
                editCustomer: "Edit Customer",
                customerName: "Customer Name",
                organization: "Organization",
                registerDate: "Register Date",
                legalPerson: "Legal Person",
                contacts: "Contacts",
                contactNumber: "Contact Number",
                phoneNumber: "Phone Number",
                aptitude: "Aptitude",
                personNumber: "Person Number",
                officeAddress: "Office Address",
                registerAddress: "Register Address",
                remark: "Remark",
            },
            group: {
                editGroup: "Edit Group",
                groupName: "Group Name",
                groupNameTip: "Not more than 50 words",
                mintime: "Min reporting time",
                maxtime: "Max reporting time",
                mintimeTip: "Shortest interval",
                maxtimeTip: "Longest interval",
                userCount: "User count",
                userCountTip: "Quantity to be included",
                devCount: "Device count",
                devCountTip: "Number of equipment included",
                addMonitors: "Adding monitors",
                noMonitors: "There is no monitor user yet. Please add it first.",
                monitors: "Monitors"
            },
            user: {
                allDev: "All Device",
                editUser: "Edit User",
                userInfo: "User Information",
                userAuthority: "User Authority",
                username: "Username",
                password: "Password",
                checkPwd: "Password Check",
                deadline: "Deadline",
                userType: "User Type",
                client: "Client",
                grouping: "Grouping",
                simultaneousLogin: "Simultaneous login",
                phoneLogin: "Phone login",
                wxLogin: "WeChat login",
                groupCount: "Group number",
                add: "Add",
                devType: "Device type",
                cmdName: "Cmd name",
                cmdPwd: "Cmd password",
                save: "Save",
                allow: "Allow",
                ban: "Ban",
                createTime: "Create date",
                resetPwd: "Reset Pwd",
                corporateName: "Corporate name",
                name: "User name",
                phone: "Phone",
                address: "Address",
                weChat: "WeChat",
                moreLanding:"moreLanding",
                creater:'creater',
            },
            device: {
                editDev: "Edit Device",
                loginPwd: "Login Pwd",
                pwdTips: "Default device number after four digits",
                reportCount: "Report count",
                allReportCount: "all report count",
                allowLogin: "Allow login",
                isUse: "Is use",
                devIdTips: "The serial number of the device must be between 8 and 15 bits.",
                exportCurrentDevice:'Export current device',
                exportAllDevice:"Export all device",
                daysOverdue7:"7 days expired",
                daysOverdue60:"60 days expired",
                expired:"Expired",
                oilMarking:"Oil marking",
                ioConfig:"IO config",
                insureInfo:"Insure info",
                speedingSetting:"Speeding setting",
                networkType:"Network type",
                forwardAddress:"Forward",
                tutelageUser:"Tutelage user",
                subEeditor:"Sub eeditor",
                contact1:"Contact1",
                contact2:"Contact2",
                gender:"Gender",
                man:"man",
                girl:"girl",
                securityNumber:"Security Id",
                insuranceDate:"Insurance date",
                effectiveDate:"Effective date",
                insureRemarks:"Remarks",
                ioNumber:"IO Number",
                io1Open:'io1 Open',
                io2Open:'io2 Open',
                io3Open:'io3 Open',
                io4Open:'io4 Open',
                io1Close:'io1 Close',
                io2Close:'io2 Close',
                io3Close:'io3 Close',
                io4Close:'io4 Close',
                importDeviceidsTips:'Serial number of the device to import',
                copy:'Copy',
                threshold:'Threshold',
                thresholdDesc:'Through the threshold to determine the state of vehicle refueling / oil leakage, according to the size of the vehicle fuel tank to set the appropriate threshold',
                tankShape:'Tank shape',
                noTank:'noTank',
                cuboid:'cuboid',
                verticalCylinder:'Vertical cylinder',
                transverseCylinder:'Transverse cylinder',
                irregular:'irregular',
                tankVolume:'Tank volume',
                sensorLength:'Sensor length',
                maxAnalogQuantity:'Max analog quantity',
                tankLength:'Tank length',
                tankWidth:'Tank length',
                tankHeight:'Tank height',
                tankDiameter:'Tank diameter',
                scale:'Scale',
                calibratedFluid:'Calibrated fluid',
                import:'Import',
                addTempInfo:'Add template',
                templateName:'Template name',
                required:'(Required)',
                oilRodBrand:'Brand',
                OilRodModel:'Model',
                templateList:'Template',
                mergeStatistical:'Merge statistical',
                addTemplate:'Add template',
                allTemplate:'All template',
                filterTemplate:'Filter template',
                queryTemplate:'Query template',
                insureCompany:'Insure company',
                oil1:'oil1',
                oil2:'oil2',
                brand:'Brand',
                model:'Model',
                tankParameters:'Tank parameters',
                importSucc:'Import succeeded',
                inputDeviceId:'Please fill in the reference equipment serial number',
                dataEmptyTips:'No data was found',
                requiredTempName:'Template name is required',
                tempSaveSucc:'Template saved successfully',
                tempSaveFail:'Template save failed',
                scaleAlreadyExists:'The scale already exists',
                calibration:'calibration',
                idLength:'ID lenth',
                copyBatchNumber:'Copy batch number',
                actionSucc:'The operation was successful',
                actionFail:'operation failed',
                notOperated:'Not operated',
                noDevice:'No device',
                passwordError:'Password error',
                abnormalInstructionIssued:'Abnormal instruction issued',
                pwdLengthTips:'Password must be greater than or equal to 4 digits',
                exportErrorTips:'The imported device does not exist in this account, please confirm',
                selectedTransferGroup:'Please select the group you want to transfer into',
                scale:'Scale',
            },
            insure:{
                templateDownload:'Template download',
                importFile:'Import file',
                ownerName:'Owner name',
                addStatus:'Add status',
                notSubmitted:'Not submitted',
                submitSucc:'Submitted successfully',
                importOwnerNameTips:'Please import owner information',
                remove:'Remove',
                importSucceeded:'Import succeeded',
                importFailed:'Import failed',
                importTimeout:'Import timeout',
                total:'Total',
                fail:'fail',
                importExcelTips:'Please use the template provided by us to import the data',
                importExcelFailTips:'Table data import failed',
                factory:'Factory',
            }
        },
        //简体中文
        zh: {
            message: {  
                changeSucc: "修改成功",
                changeFail: "修改失败", 
                addSucc: "添加成功",
                addFail: "添加失败",
                saveSucc: "保存成功",
                saveFail: "保存失败",
                deleteSucc: "删除成功",
                deleteFail: "删除失败",
                noAuthority: "没有权限",
                confirmDel: "确定要删除吗?",
                selectCustomersTip: "请选择所属客户",
                fillGroupNameTip: "填写分组名称",
                pwdRule: "密码小于6位",
                usernameRule: "用户名是4到32位的数字和字母组成的",
                fullComplete: "请填写完整",
                fullDevName: "请填写设备名称",
                userExists: "该用户已存在",
                resetPwdTips: "密码重置为:123456",
                plSelectTime: "请选择时间",
                IDRepeat: "设备序号重复",
                IDError: "设备序号错误",
                reqFail: "请求失败",
                selectCorrectAccount: "请选择正确的账号!",
                networkError: "网络错误",
                exportSucceeded: "导出成功",
                exportFailed: "导出失败",
                useTemplateTips: "请使用我们提供的模版填写",
                selectDeviceTtypeTips: "请选择设备类型",
                addDevice500Tips: "一次添加设备不得超过500",
                deviceIdTips: "序列号必须是数字或者字母",
            },
            login: {
                title: "车载视频安全预警平台",
                chinese: "中文",
                english: "English",
                companyLogin: "用户登录",
                deviceLogin: "设备登录",
                pememberPwd: "记住密码",
                logining: "登录",
                experience: "我要体验",
                inputUsername: "请输入账号",
                inputDeviceNumber: "请输入设备号",
                inputPassword: "请输入密码",
                wechatApplet: "微信小程序",
                step1: "1.在微信中搜索gps51小程序",
                step2: "2.或者直接扫描二维码",
                step3: "3.适用于iPhone/Android",
                appdownload: "App应用下载",
                appstep1: "1.在应用市场搜索gps51",
                appstep2: "2.或者直接扫描二维码",
                appstep3: "3.适用于iPhone/Android",
                error_1: "账号不能为空或者账号太短",
                error_2: "密码不能为空或者密码太短",
                error_3: "登录失败",
                error_4: "账号或密码错误",
                error_5: "禁止登陆",
                error_6: "账号过期",
                beiAn1: "Copyright © 2015-2017 gps51.com All Rights Reserved",
                beiAn2: "粤ICP备17068924号",
            },
            header: {
                monitor: "实时监控",
                reportForm: "统计报表",
                bgManager: "后台管理",
                systemParam: "系统参数",
                ruleManagr: "规则管理",
                hello: "您好",
                changePwd: "修改密码",
                multiSiteLanding: "多点登陆",
                setting: "设置", 
                logout: "退出",
                showCustomer: "显示分组所属客户",
                setIntaival: "刷新间隔(最小5秒)",
                oldPwd: "旧密码",
                newPwd: "新密码",
                confirmPwd: "确认密码",
                submit: "提交",
                changePwdSucc: "密码修改成功",
                error_1: "密码不能小于四位",
                error_2: "密码不能为空",
                error_3: "2次密码不一致",
                error_4: "旧密码错误",
                contact: "联系客服",
                info: "客服信息",
                name: "客服名称",
                phone: "手机号码",
                wechat: "微信号",
                email: "邮箱",
                yes:"是",
                no:"否",
            },
            alarm: {  
                message: "消息",
                alarmMsg: "报警消息",
                devMsg: "设备信息",
                filterAlarmType: "过滤报警类型",
                open: "展开",
                min: "最小化",
                max: "最大化",
                changeWin: "切换窗口",
                filterAlarmTitle: "过滤器报警",
                releaseAlarmTitle: "解除报警",
                errorNeedParams: "所有参数都是必填的",
                successfulRelease: "解除成功",  
                devName: "设备名称", 
                devNum: "设备序号", 
                alarmTime: "报警时间",
                alarmCount: "报警次数",
                isDispose: "是否处理",
                action: "操作",
                alarmDispose: "报警处理",
                overdueTime: "过期时间",
                isOverdue: "是否过期",
                createTime: "创建时间",
                content: '内容',
                expirationInfo: '过期信息',
                emergencyAlarm: '紧急报警',
                voice: '声音',
                popup: '弹窗',
                emergencyAlarmSetting: '紧急报警设置',
            },
            monitor: {        
                mapMode:'地图模式',
                videoMode:'视频模式',
                screenDisplay:'大屏展示',
                regionSelection:'区域选择',
                defaultStyle:'模式样式',
                midnightBlue:'午夜蓝',
                stock:'库存',
                ownerInfo:'车主信息',
                gotogroup:'转至分组',
                play:'播放',
                batteryMgr:'电池管理',
                weigh:'称重',
                watermeter:'水表',
                videoSettings:'视频设置',
                intercom:'对讲',
                devGroup: "设备组",
                defaultGroup: "默认组",
                defaultCustomer: "默认客户",
                all: "全部",
                online: "在线",
                offline: "离线",
                placeholder: "输入设备名称",
                edit: "编辑",
                track: "轨迹",
                following: "跟踪",
                more: "更多",
                deviceCmd: "设备指令",
                siteProtection: "原地设防",
                fortify: "设防",
                cancel: "撤防",
                cmdRecord: "指令记录",
                recordForm: "统计报表",
                devBaseInfo: "设备基本信息",
                refreshAfter: "秒后刷新",
                ranging: "测距",
                tools: "工具",
                editDev: "编辑设备",
                phoneNumber: "手机号码",
                remarks: "备注",
                confirm: "确定",
                customer: "所属客户",
                groupName: "分组名称",
                devNumber: "设备序号",
                devName: "设备名称",
                factoryNum: "厂商编号",
                clientType: "终端型号",
                expireTime: "到期时间",
                close: "关闭",
                settingFence: "设置电子围栏",
                range: "范围(米)",
                toSendCmd: "待发送指令",
                directivesSent: "已发送指令",
                settingFail: "设置失败",
                noTrackError: "该设备没有轨迹,无法设防",
                rangeNumErr: "范围必须是数字",
                queryCmdRecordErr: "查询指令记录失败",
                cancelFenceSucc: "撤防成功",
                sendSucc: "下发成功",
                pwdErr: "密码错误",
                sendCmdAbnormal: "下发指令异常",
                sendCmdNoCache: "设备离线,指令没有缓存",
                sendCmdAlreadyCache: "设备离线,指令已经缓存",
                changePwdSendCmd: "请修改默认密码后再发送指令",
                noRecordTrack: '该设备没有上报位置信息',
                reLogin: "请重新登录,2秒后自动跳转登录页面",
                devNameMust: "设备名称是必填的",
                alarmRecords: "报警记录",
                media: "录音",
                clearAllVideos:'清除所有视频',
                mute:'静音',
                showAChannel:'显示一个通道',
                showFourChannel:'显示四个通道',
                showSixChannel:'显示六个通道',
                showEightChannel:'显示八个通道',
                showNineChannel:'显示九个通道',
                showSixteenChannel:'显示十六个通道',
                playAllVideos:'播放所有视频',
                stopAllVideos:'停止所有视频',
                videoPlayback:'视频回放',
                activeSafety:'主动安全',
                recordingTips:'正在录音,请说话',
                yuntai:'云台',
                call:'调用',
                setup:'设置',
                delete:'删除',
                color:'色彩',
                luminance:'亮度',
                contrastRatio:'对比度',
                chroma:'色度',
                saturation:'饱和度',
                exposure:'曝光',
                default:'默认',
                voice:'语音',
                monitor:'监听',
                close:'关闭',
                open:'开启',
                repressSpeak:'按住通话',
                audioPlayerTip:'对讲请先点击以下按钮',
                openJianTingTip:'请先开启监听',
                openJianTingTip1:'监听已打开，请按住说话',
                browserDoesNotSupportRecording:'浏览器不支持录音功能或者没有检测到录音设备',
                closeSucc:'关闭成功',
                openSucc:'开启成功',
                openFail:'开启失败,超时或者设备不在线',
                jiantingYiclose:'监听已关闭',
                selectVideoDevice:'请选择视频设备',
                channelIsNumber:'通道号必须是1到99的数字',
                setupSucc:'设置成功',
                setupFail:'设置失败',
                querySucc:'查询成功',
                queryFail:'查询失败',
                theDeviceDidNotReturnData:'设备没有返回数据',
                CMD_SEND_RESULT_UNCONFIRM:'发送成功，未收到确认',
                CMD_SEND_CONFIRMED:'发送成功',
                CMD_SEND_RESULT_PASSWORD_ERROR:'密码错误',
                CMD_SEND_RESULT_OFFLINE_NOT_CACHE:'设备离线，未缓存',
                CMD_SEND_RESULT_OFFLINE_CACHED:'设备离线，已缓存',
                CMD_SEND_RESULT_MODIFY_DEFAULT_PASSWORD:'需要修改默认密码',
                CMD_SEND_RESULT_DETAIL_ERROR:'错误:',
                CMD_SEND_OVER_RETRY_TIMES:'尝试发送3次失败',
                CMD_SEND_SYNC_TIMEOUT:'发送超时',
                transferSucc:'转移成功',
                transferFail:'转移失败',
                fillParameters:'请填写全部参数',
                channel:'通道',
                mapNotSupported:'该地图暂时不支持该功能',
                deviceOffline:'设备离线',
                deviceNotVideo:'该设备不是视频机',
                notEnabled:" [未启用] ",
            },
            video:{
                accOpen:'ACC开,',
                accClose:'ACC关,',
                requestTimeout:'请求超时',
                requestPlayTimeout:'请求播放超时...',
                requestPlaySucc:'请求播放成功,请稍后...',
                error:'请求数据时遇到错误',
                requestPlay:'正在请求播放',
                play:'开始播放',
                playing:'正在播放',
                pause:'暂停',
                waiting:'等待数据',
                pausePlay:'暂停播放',
                threeMinutes:'已播放三分钟时间,暂停播放',
                notSupportCanvas:"您的浏览器暂不支持canvas",
            },
            reportForm: {           
                empty:'空', 
                clean:'清除',
                total: "合计 : ",
                maxMileage: "结束里程",
                minMileage: "起始里程",
                totalMileage: "总里程",
                date: "日期",
                index: "编号",
                drivingReport: "行驶报表",
                cmdReport: "命令报表",
                posiReport: "位置报表",
                mileageReport: "里程报表",
                mileage: "里程",
                reportmileagesummary: "里程总览",
                reportmileagedetail: "里程详单",
                parkDetails: "停留详单",
                warningReport: "报警报表",
                allAlarm: "全部报警",
                phoneAlarm: "电话报警",
                rechargeRecords: "充值记录",
                selectTime: "选择时间",
                selectDev: "选择车辆",
                toDay: "今天",
                yesterDay: "昨天",
                threeDays: "最近三天",
                sevenDays: "最近七天",
                query: "查询",
                intervalTime: "间隔时间(分)",
                selectDevTip: "请选择设备",
                noRecord: "没有记录",
                sendDate: "发送时间",
                content: "发送内容",
                sendResult: "发送结果",
                lon: "经度",
                lat: "纬度",
                direction: "方向",
                speed: "速度",
                time: "时间",
                status: "状态",
                posiType: "定位类型",
                address: "地址",
                AddressDetails: "位置明细",
                getAddress: "获取地址",
                seePosi: "查看位置",
                startAlarmDate: "开始报警时间",
                lastAlarmDate: "最后报警时间",
                alarmInfo: "报警信息",
                alarmCount: "报警次数",
                isDispose: "是否处理",
                disposePerson: "处理人",
                untreated: "未处理",
                handled: "已处理",
                startDate: "开始时间",
                endDate: "结束时间",
                parkDate: "停留时间",
                d: "天",
                h: "小时",
                m: "分",
                s: "秒",
                acc: "ACC报表",
                accstatus: 'ACC状态',
                duration: '时长',
                open: '开启',
                stalling: '熄火',
                notEnabled: '未启用',
                accOffTime: '熄火时长',
                accOnTime: '开启时长',
                accDetailed: '点火明细',
                accCount: '点火次数',
                accStatistics: '点火统计',
                accDuration: '点火时长',
                ignitionStatistics: '点火统计数据',
                download:'下载',
                filter:'过滤',
                beforeDay:'上一天',
                afterDay:'下一天',
                voiceReport:'语音报表',
                messageReport:'报文报表',
                rotationStatistics:'正反转统计',
                rotationDetails:'正反转明细',
                count:'次数',
                zzTimes:'正转时长',
                fzTimes:'反转时长',
                tzTimes:'停转时长',
                zz:'正转',
                fz:'反转',
                tz:'停转',
                wechatAlarm:'微信报警',
                speedingReport:'超速报表',
                speedingStatistics:'超速统计',
                speedingDetails:'超速明细',
                speedingDuration:'超速时长',
                speedingMileage:'超速里程',
                speedingCount:'超速次数',
                maxSpeed:'最大速度',
                minSpeed:'最小速度',
                speedingTrack:'超速轨迹',
                onlineStatistics:'上线统计',
                comprehensiveStatistics:'综合统计',
                offlineReport:'离线报表',
                dailyVehicleOnlineRate:'车辆日在线率',
                dailyFleetOnlineRate:'车队日在线率',
                monthlyVehicleOnlineRate:'车辆月在线率', 
                operationStatus:'运营状态',
                updateTime:'更新时间',
                lastAddress:'最后位置',
                lastState:'最后状态',
                notLocated:'未定位',
                located:'已定位',
                selectAccount:'选择账号',
                vehicleTotal:'车辆总数',
                onlineTotal:'在线数量',
                offlineTotal:'离线数量',
                locationTotal:'定位数量',
                notLocationTotal:'不定位数量',
                offlineDuration:"离线时长大于",
                h1:"1小时",
                h6:"6小时",
                h12:"12小时",
                d1:"1天",
                d7:"7天",
                d15:"15天",
                d30:"1个月",
                d180:"半年",
                d365:"一年",
                offlineTime:"掉线时间",
                downOfflineDuration:"掉线时长",
                ascriptionUser:"所属账号",   
                selectMonth:"选择月份",
                onlineDaysAndTotalDays:"在线天数/总天数",
                onlineRate:"在线率",
                onlineDate:"在线日期",
                selectDate:"选择日期",
                onlinequantityAndTotalquantity:"在线数量/总数量",
                dailyOnlineRate:"日在线率",
                selectGroup:"请选择分组",
                insurMgr:'保险管理',
                insurRecord:'保险记录',
                salesRecord:'销售记录',
                all:'全部',
                aeviewed:'已审核',
                notReviewed:'未审核',
                exactSearch:'精确查找',
                exportData:'导出数据',
                examine:'是否审核',
                name:'姓名',
                idNumber:'身份证号',  
                policyNumber:'保单号',
                addDate:'添加时间',
                purchaseMethod:'购买方式',
                distributor:'经销商',
                distributorAddress:'经销商地址',
                distributorPhone:'经销商手机号',
                phonenum: '用户手机号',
                usingaddress: '用户地址', 
                brandtype: '品牌型号', 
                vinno: '车架号', 
                gpsid: 'GPS序列号',
                buycarday: '购车日期', 
                carvalue: '销售价格', 
                insureprice: '保险金额', 
                insurefee: '保费', 
                qualitycert: '合格证',
                carpic: '整车照',
                positivecardid: '身份证正面',
                negativecardid: '身份证反面',
                invoice: '购车发票',
                groupphoto: '车主与车合影',
                carkeypic: '车钥匙/遥控器',
                insurenotice: '保险告知书',
                clickPreview: '点击预览',
                cancelAudit: '取消审核',
                confirmAudit: '确认审核',
                underReview: '保单审核中',
                insureData: '保险数据',
                tips:'提示',
                tipsContent: "是否删除这个保单信息!",
                storeNumber:'门店编号',
                storeName:'门店名称',
                cumulativeRecords:'累计保险充值记录',
                surplus:'剩余保单数',
                exFactory:'出厂已购保单销售数',
                buyOneself:'自行购买保单销售数',
                year:'年',
                month:'月',
                insurePlaceholder:'输入_姓名|手机号|身份证号',
                oilReport:'油液报表',
                dayOilConsumption:'日行油液报表',
                dateOilConsumption:'时间油液报表',
                addOil:'加油液报表',
                reduceOil:'漏油液报表',
                tempReport:'温湿度报表',
                logisticsReport:'物流报表',
                driverWorkDetails:'司机工作明细',
                oilConsumption:'油耗',
                fuelVolume:'加油液量',
                oilLeakage:'漏油液量',
                fuelConsumption100km:'百公里油耗',
                soil:'加油液前油液量(L)',
                eoil:'加油液后油液量(L)',
                lsoil:'漏油液前油液量(L)',
                leoil:'漏油液后油液量(L)',
                saddress:'开始位置(点击获取位置)',
                eaddress:'结束位置(点击获取位置)',
                totalOil:'总油液(L)',
                oil1:"油液1(L)",
                oil2:"油液2(L)",
                oil:"油液",
                temp:'温度',
                temp1:'温度1',
                temp2:'温度2',
                temp3:'温度3',
                temp4:'温度4',
                averageTemp:'平均温度',
                humi:'湿度',
                drivername:'司机名称',
                cardinsertTime:'装点时间(插卡)',
                cardinsertAddress:'装点地点(插卡)',
                cardPullTime:'卸点时间(拔卡)',
                cardPullAddress:'卸点地点(拔卡)',
                workingHours: '工作时长',
                certificationcode: '驾驶证号',
                viewTrack: '查看轨迹',
                queryAllAddress: '一键查询地址',
            },
            bgMgr: {    
                bindpwd: "绑定密码",
                customerMgr: "客户管理",
                addCustomer: "添加客户",
                queryCustomer: "查询客户",
                groupMgr: "分组管理",
                addGroup: "添加分组",
                queryGroup: "查询分组",
                userMgr: "用户管理",
                addUser: "添加用户",
                queryUser: "查询用户",
                devMgr: "设备管理",
                addDev: "添加设备",
                queryDev: "查询设备",
                submit: "提交",
                reset: "重置",
                back: "返回",
                delete: "删除",
                edit: "编辑",
                action: "操作",
                userTotal: "用户总数",
                deviceTotal: "设备总数",
                groupTotal: "分组总数",
                addTime: "添加时间",
                creater: "创建者",
                batchMgr: "批量管理",
                batchAdd: "批量添加",
                renewMgr: "续费管理",
                operateMgr: "运营管理",
                importOwnerInfo: "导入车主信息",
                importInsureInfo: "导入保险信息",
                importPolicyInfo: "导入保单信息",
                importVin: "导入车架号",
                importOfflineInsurePolicyInfo: "导入线下保单信息",
                importSimInfo: "导入SIM卡信息",
                importDeviceName: "导入设备名称",
                repairMgr: "维修管理",
                addRepair: "添加记录",
                repairRecord: "维修记录",
                allAevcieList: "全部设备列表",
                selectedDeviceList: "已选中设备列表",
                transferGroupList: "转入用户分组列表",
                result:"结果",
                exportDevice:"导入设备",
                batchModification:"批量修改",
                batchTransfer:"批量转移",
                batchModifyForwardingAddress:"批量修改转发地址",
                batchEditDueDate:"批量修改到期时间",
                batchResetPwd:"批量重置密码",
                batchEditDevType:"批量修改设备类型",
                batchIssueCmd:"批量下发指令",
                forwardingType:"转发类型",
                parseHttp:"解析后HTTP",
                tcp:"原数据TCP",
                passModel:"密码模式",
                deviceIDlastFour:"设备号后四位",
                fixedPassword:"固定密码",
                issueCmd:"下发指令",
                cmdContent:"指令内容",
                pwd:"密码",
                sending:"正在发送中",

            },
            customer: {
                kehuName: "客户名称",
                editCustomer: "编辑客户",
                customerName: "企业名称",
                organization: "组织机构编号",
                registerDate: "注册时间",
                legalPerson: "法人代表",
                contacts: "企业联系人",
                contactNumber: "联系电话",
                phoneNumber: "24小时联系电话",
                aptitude: "运营资质类别",
                personNumber: "企业员工人数",
                officeAddress: "办公地址",
                registerAddress: "注册地址",
                remark: "备注",

            },
            group: {
                editGroup: "编辑分组",
                groupName: "分组名称",
                groupNameTip: " 分组名称(最大不能超过50个字符!)",
                mintime: "最短定位时间",
                maxtime: "最长定位时间",
                mintimeTip: "车辆可设置定位间隔的下限(最短间隔)",
                maxtimeTip: "车辆可设置定位间隔的上限(最长间隔)",
                userCount: "用户数量",
                userCountTip: "可包含的监控员数量",
                devCount: "设备数量",
                devCountTip: "可包含的车辆数量",
                addMonitors: "添加监控员",
                noMonitors: " 暂无监控员用户,请先添加",
                monitors: "选择监控员"
            },
            user: {  
                allDev: "所有设备",
                editUser: "编辑用户",
                userInfo: "用户信息",
                userAuthority: "用户权限",
                username: "用户名",
                password: "密码",
                checkPwd: "确认密码",
                deadline: "过期时间",
                userType: "用户类型",
                client: "所属客户",
                grouping: "所属分组",
                simultaneousLogin: "同时登录",
                phoneLogin: "手机登录",
                wxLogin: "微信登录",
                groupCount: "分组数量",
                add: "添加",
                devType: "设备类型",
                cmdName: "命令名称",
                cmdPwd: "命令密码",
                save: "保存",
                allow: "允许",
                ban: "禁止",
                createTime: "创建时间",
                resetPwd: "重置密码",
                corporateName: "公司名称",
                name: "真实姓名",
                phone: "电话",
                address: "地址",
                weChat: "微信",
                moreLanding:"多点登录",
                creater:'创建者',
            },
            device: {   
                editDev: "编辑设备",
                loginPwd: "登录密码",
                pwdTips: "默认设备序号后四位",
                reportCount: "上报次数",
                allReportCount: "总上报次数",
                allowLogin: "允许登录",
                isUse: "是否使用",
                devIdTips: "设备序号必须是8-15位之间的",
                exportCurrentDevice:"导出当前设备",
                exportAllDevice:"导出全部设备",
                daysOverdue7:"7天内过期",
                daysOverdue60:"60天内过期",
                expired:"已过期",
                oilMarking:"油液标注",
                ioConfig:"IO配置",
                insureInfo:"保险信息",
                speedingSetting:"超速设置",
                networkType:"网络类型",
                forwardAddress:"转发地址",
                tutelageUser:"监护账号",
                subEeditor:"下级编辑",
                contact1:"联系方式1",
                contact2:"联系方式2",
                gender:"性别",
                man:"男",
                girl:"女",
                securityNumber:"防盗号",
                insuranceDate:"投保日期",
                effectiveDate:"生效日期",
                insureRemarks:"保险备注",
                ioNumber:"IO个数",
                io1Open:'io1开',
                io2Open:'io2开',
                io3Open:'io3开',
                io4Open:'io4开',
                io1Close:'io1关',
                io2Close:'io2关',
                io3Close:'io3关',
                io4Close:'io4关',
                importDeviceidsTips:'要导入的设备序号',
                copy:'参考',
                threshold:'阀值',
                thresholdDesc:'通过阀值来判定车辆加油/漏油状态，根据车辆的油箱大小设置合适的阀值',
                tankShape:'油箱的形状',
                noTank:'无油箱',
                cuboid:'长方体',
                verticalCylinder:'竖圆柱体',
                transverseCylinder:'横圆柱体',
                irregular:'不规则',
                tankVolume:'油箱的容积',
                sensorLength:'传感器长度',
                maxAnalogQuantity:'最大模拟量',
                tankLength:'油箱的长度',
                tankWidth:'油箱的宽度',
                tankHeight:'油箱的高度',
                tankDiameter:'油箱的直径',
                scale:'标定的刻度',
                calibratedFluid:'标定的油液',
                import:'导入',
                addTempInfo:'添加模版信息',
                templateName:'模版名称',
                required:'(必填)',
                oilRodBrand:'油杆品牌',
                OilRodModel:'油杆型号',
                templateList:'模版列表',
                mergeStatistical:'油箱合并统计',
                addTemplate:'添加模版',
                allTemplate:'全部模版',
                filterTemplate:'过滤模版',
                queryTemplate:'查询模版',
                insureCompany:'保险公司',
                oil1:'油液1',
                oil2:'油液2',
                brand:'品牌',
                model:'型号',
                tankParameters:'油箱参数',
                importSucc:'导入成功',
                inputDeviceId:'请填写参考设备序号',
                dataEmptyTips:'没有查询到数据',
                requiredTempName:'模版名称是必填的',
                tempSaveSucc:'模版保存成功',
                tempSaveFail:'模版保存失败',
                scaleAlreadyExists:'该刻度已存在',
                calibration:'测量标定',
                idLength:'序号长度',
                copyBatchNumber:'复制批量序号',
                actionSucc:'操作成功',
                actionFail:'操作失败',
                notOperated:'未操作',
                noDevice:'没有该设备',
                passwordError:'密码错误',
                abnormalInstructionIssued:'下发指令异常',
                pwdLengthTips:'密码必须大于或等于4位数',
                exportErrorTips:'导入的设备不存在该账户下，请确认',
                selectedTransferGroup:'请选择要转入的组',
                scale:'刻度',
            },
            insure:{
                templateDownload:'模版下载',
                importFile:'导入文件',
                ownerName:'车主姓名',
                addStatus:'添加状态',
                notSubmitted:'未提交',
                submitSucc:'提交成功',
                importOwnerNameTips:'请导入信息',
                remove:'移除',
                importSucceeded:'导入成功',
                importFailed:'导入失败',
                importTimeout:'导入超时',
                total:'总共',
                fail:'失败',
                importExcelTips:'请使用我们提供的模版导入数据',
                importExcelFailTips:'表格数据导入失败',
                factory:'厂商',
            }
        }
    }

    win.messages = messages;
})(this)